version: "3.7"

services: 

##########################
##         NGINX        ##
## nginx:1.17.1-alpine ##
##########################
  nginx:
    build: 
      context: .
      dockerfile: ./docker-config/alpine-nginx/Dockerfile
    networks:
      - backend
    ports:
      - 80:80
    volumes:
      - cpresources:/var/www/html/web/cpresources
    container_name: nginx


########################
##        CRAFT       ##
## php:7.2-fpm-alpine ##
########################
  php:
    build: 
      context: .
      dockerfile: ./docker-config/alpine-php/Dockerfile
    networks:
      - backend
    expose:
      - 9000
    volumes:
      - cpresources:/var/www/html/web/cpresources
    environment:
      ENVIRONMENT: "${ENVIRONMENT}"
      DB_DRIVER: "${DB_DRIVER}"
      DB_SERVER: "${DB_SERVER}" # Named after db name
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_DATABASE: "${DB_DATABASE}"
      DB_SCHEMA: "${DB_SCHEMA}"
      DB_TABLE_PREFIX: "${DB_TABLE_PREFIX}"
      SITE_URL: "${SITE_URL}"
      SECURITY_KEY: "${SECURITY_KEY}"
    container_name: craft



######################
##      MARIADB     ##
##  mariaDB:10.4.4  ##
######################
  mariadb:
    image: mariadb:10.4.4
    restart: always
    environment:
      TZ: America/Los_Angeles
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
    networks:
      - backend
    expose:
      - 3600
    ports:
      - 3306:3306
    volumes:
      - ${DB_DATABASE}:/var/lib/mysql
      - ${PATH_TO_SQL_DB}:/docker-entrypoint-initdb.d/dump.sql
    container_name: mariadb


# Named volumes
volumes: 
  cpresources: #default driver: "local"
  mariadb-data:

# Networks
networks:
  backend: #default driver: bridge