version: "3.7"

# Named volumes
volumes: 
  mysql-data:

services:
  # MySQL database
  mysql-data:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: "mysql-data"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysql-data:/var/lib/mysql
