version: "3.7"

services: 

##########################
##         NGINX        ##
## nginx:1.15.12-alpine ##
##########################
  nginx:
    build: 
      context: .
      dockerfile: ./docker-config/alpine-nginx/Dockerfile
    links:
      - php
      - mysql
    networks:
      - backend
    ports:
      - 80:80
    volumes:
      - cpresources:/var/www/html/
    container_name: nginx


########################
##        CRAFT       ##
## php:7.2-fpm-alpine ##
########################
  php:
    build: 
      context: .
      dockerfile: ./docker-config/alpine-phpfpm/Dockerfile
    networks:
      - backend
    expose:
      - 9000
    volumes:
      - cpresources:/var/www/html
    env_file:
      - ./src/.env

    # environment:
      # ENVIRONMENT: "dev"
      # DB_DRIVER: "mysql"
      # DB_SERVER: "mysql"
      # DB_USER: "root"
      # DB_PASSWORD: "password"
      # DB_DATABASE: "mysql-data"
      # DB_SCHEMA: "public"
      # DB_TABLE_PREFIX: "craft_"
      # SITE_URL: "http://localhost"
      # SECURITY_KEY: "AAAAAAAAAAAAAAAAAAAAAAAAAAA"
    container_name: craft



#############
##  MYSQL  ##
## mysql:8 ##
#############
  mysql:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: "mysql-craft"
      MYSQL_USER: "root"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    networks:
      - backend
    # ports:
    #   - 3306:3306
    expose:
      - 3306
    volumes:
      - mysql-data:/var/lib/mysql
    container_name: mysql


# Named volumes
volumes: 
  mysql-data: #default driver: "local"
  cpresources:
  
# Networks
networks:
  backend: #default driver: bridge
