version: "3.7"

services: 

##########################
##         NGINX        ##
## nginx:1.15.12-alpine ##
##########################
  nginx:
    build: 
      context: .
      dockerfile: ./docker-config/alpine-nginx/Dockerfile
    networks:
      - backend
    ports:
      - 80:80
    volumes:
      - cpresources:/var/www/html/web/cpresources
    container_name: nginx


########################
##        CRAFT       ##
## php:7.2-fpm-alpine ##
########################
  php:
    build: 
      context: .
      dockerfile: ./docker-config/alpine-php/Dockerfile
    networks:
      - backend
    expose:
      - 9000
    volumes:
      - cpresources:/var/www/html/web/cpresources
    environment:
      ENVIRONMENT: "${ENVIRONMENT}"
      DB_DRIVER: "${DB_DRIVER}"
      DB_SERVER: "${DB_SERVER}" # Named after mysql service below
      DB_USER: "${DB_USER}"
      DB_PASSWORD: "${DB_PASSWORD}"
      DB_DATABASE: "${DB_DATABASE}"
      DB_SCHEMA: "${DB_SCHEMA}"
      DB_TABLE_PREFIX: "${DB_TABLE_PREFIX}"
      SITE_URL: "${SITE_URL}"
      SECURITY_KEY: "${SECURITY_KEY}"
    container_name: craft



#############
##  MYSQL  ##
## mysql:8 ##
#############
  mysql:
    image: mysql:8
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      TZ: "${MYSQL_TZ}"
    networks:
      - backend
    expose:
      - 3306
    volumes:
      - mysql-data:/var/lib/mysql
      - ${PATH_TO_SQL_DB}:/docker-entrypoint-initdb.d/dump.sql
    container_name: mysql


# Named volumes
volumes: 
  cpresources: #default driver: "local"
  mysql-data:

# Networks
networks:
  backend: #default driver: bridge